#!/usr/bin/env python

import mcr_direct_base_controller_ros.component_wise_pose_error_calculator

if __name__ == '__main__':
    mcr_direct_base_controller_ros.component_wise_pose_error_calculator.main()
